### ISSUE TITLE
Clarify usage of branches in this repository

### ISSUE THREAD

**Issue by nox** [sfackler/rust-phf#139]
The master branch is based off 0.7.21 and diverged with the 0.7.x branch, where unicase support still exists. This is confusing.

**Comment by sfackler** [comment]
The master branch is in the middle of an overhaul I never got around to finishing. I should probably swap the branches around and make 0.7.x master.

Unicase support was removed because we didn't think anyone was using it, and IIRC Unicase's real unicode support isn't const constructable: https://github.com/sfackler/rust-phf/pull/109#issuecomment-335742412

**Comment by sfackler** [comment]
Master now corresponds to the "real" version, and the new stuff is on the next branch!
