### ISSUE TITLE
Remove ordered_[map, set], phf_builder

### ISSUE THREAD

**Issue by abonander** [sfackler/rust-phf#170]
@sfackler / https://github.com/sfackler/rust-phf/pull/168#issuecomment-513043200:
> There are two other cleanup things that may be worth considering for the 0.8 release:
> 1. Removing OrderedMap and OrderedSet. As far as I can tell, no one actually uses them.
> 2. Removing phf-builder (and with it the Cow-like enum we need to use internally). You're probably just better off using a HashMap.

Is this something worth posting an RFC (just asking for people's opinions) for on Reddit/URLO?

**Comment by abonander** [comment]
Well, I guess we can always just add them back if anyone complainss.

**Comment by cher-nov** [comment]
Well, I've just stumbled across the situation where `ordered_map` would be really helpful, and I was very discouraged to see that it's removed from the crate just for the reason of being supposedly useless. 😢 
I need to create a compile-time hashmap that maps function names to function pointers:

```rust
type KernelFunction = fn(&mut Context, &[Value]) -> kernel::Result<Value>;

pub enum Function {
    Runtime(KernelFunction),
    Pure(KernelFunction),
}

#[derive(Serialize, Deserialize)]
pub struct FunctionInfo {
    name: &'static str,
    info: &'static Function,
}

pub const FUNCTIONS: phf::Map<&'static str, Function> = phf_map! {
    "sin" => Function::Pure( Kernel::sin ),
    "cos" => Function::Pure( Kernel::cos ),
    "draw" => Function::Runtime( Kernel::draw ),
}
```

The problem is that `FunctionInfo` should support serialization / deserialization by [Serde](https://serde.rs), but function pointers aren't serializable, so I must write corresponding trait implementations by myself. And there's only two options available for it:

- serialize by function name and deserialize by map lookup;
- serialize by map index and deserialize by index access.

The second is much more preferred as it requires much less space in the resulting serialization, but for this the ordered map is required. Because of this, I am forced to use the old 0.7.54 version instead of 0.8 which is the latest.

**Comment by dominusmi** [comment]
I also have just found myself in a position where an ordered map would be very useful
