### ISSUE TITLE
error: unsupported key expression with const keys

### ISSUE THREAD

**Issue by j1elo** [sfackler/rust-phf#186]
I'd like to do the following (simplified code):

```
type CheckCode = i32;

const CHECK_TYPE_1: CheckCode = 100;
const CHECK_TYPE_2: CheckCode = 101;
const CHECK_TYPE_3: CheckCode = 110;

static MY_MAP: phf::Map<CheckCode, i32> = phf_map! {
    CHECK_TYPE_1 => 999,
    CHECK_TYPE_2 => 888,
    CHECK_TYPE_3 => 777,
};
```

However the code doesn't compile with `error: unsupported key expression`. I've seen in a similar issue that `phf_map` requires annotated key types, but here they are perfectly annotated and in fact it is not possible to add type annotations to the const names (afaik).

Is doing this possible at all with phf?

**Comment by j1elo** [comment]
I just realized I can just write a function with a match expression, given that for my case everything is an integer. But I'm curious about why this expression is not valid for phf...

**Comment by abonander** [comment]
`phf_map!()` doesn't just expand to a `match` block, although that might be a viable way to implement a const map in current Rust. The implementation of the macro needs to know the actual values of the keys to calculate the lookup tables for the map, but unfortunately the macros can't inspect the values of the consts, all they see are the names.

We theoretically could use `const fn`s instead of macros, in which case you could use `const`s as keys, but the language support isn't quite there yet. I'm going to close this in favor of #188 where that's being discussed.

**Comment by Luctins** [comment]
@abonander can you please re-open this? as it is still relevant and the [other issue](#188) ended up being closed thinking this was more recent.

**Comment by abonander** [comment]
I'm no longer a maintainer on this project. I recommend opening a new issue or pinging someone else.
