### ISSUE TITLE
Runtime generation of PHF maps?

### ISSUE THREAD

**Issue by aochagavia** [sfackler/rust-phf#79]
Does generating PHF maps at runtime fit the scope of this library? I would like to experiment with the idea, even if it ends up in a different crate. Any pointers on where to begin?

**Comment by sfackler** [comment]
It's not supported right now, but it definitely seems like a thing that would make sense to have. It would probably end up as another crate in this repo. The implementation will be very similar to that in [phf_codegen](https://github.com/sfackler/rust-phf/blob/master/phf_codegen/src/lib.rs) except that the build methods would construct the relevant type directly instead of generating source text.

**Comment by sfackler** [comment]
I was actually a little bit into implementing this but it'll unfortunately be a bit less straightforward than I originally hoped. The types in the phf crate use `&'static [T]`s for lookup tables which are incompatible with runtime generation unless we want to leak a bunch of `Vec<T>`s which is not great. This'll probably require a larger refactor to abstract the functionality to something that can work with both &'static [T] and Vec<T>s.

**Comment by aochagavia** [comment]
I have also been working at it and the only alternative was to create a new type, like the one below:

```rust
pub struct RuntimeMap<K, V> {
    key: u64,
    pub disps: Vec<(u32, u32)>,
    pub entries: Vec<(K, V)>,
}
```

This way you don't need to leak anything. The big drawback of this approach is that it requires duplicating a lot of code or refactoring the current one.

**Comment by sfackler** [comment]
The regex crate has similar issues - might be worth looking and seeing how they handle this.
